### ISSUE TITLE
can't inflate rich editor inside viewpager

### ISSUE THREAD

**Issue by abfist** [wasabeef/richeditor-android#112]
im trying to use the richeditor inside a viewpager, using the exact same layout  of the sample 
unforunatlly i recieve a problem with inflating the view when run from this function:

```
@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		View view=inflater.inflate(R.layout.l_f_text_rich_editor,container,false);
		initEditor(view);
		_Preview = (TextView) view.findViewById(R.id.preview);
		return view;
	}
```

```
04-21 18:08:13.871: E/AndroidRuntime(15324): FATAL EXCEPTION: main
04-21 18:08:13.871: E/AndroidRuntime(15324): Process: com.example.storyteller, PID: 15324
04-21 18:08:13.871: E/AndroidRuntime(15324): android.view.InflateException: Binary XML file line #266: Binary XML file line #266: Error inflating class jp.wasabeef.richeditor.RichEditor
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.LayoutInflater.inflate(LayoutInflater.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at com.example.storyteller.FragmentCreateText.onCreateView(FragmentCreateText.java:30)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.View.measure(View.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.Choreographer.doCallbacks(Choreographer.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.Choreographer.doFrame(Choreographer.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.os.Handler.handleCallback(Handler.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.os.Handler.dispatchMessage(Handler.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.os.Looper.loop(Looper.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.app.ActivityThread.main(ActivityThread.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at java.lang.reflect.Method.invoke(Native Method)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
04-21 18:08:13.871: E/AndroidRuntime(15324): Caused by: android.view.InflateException: Binary XML file line #266: Error inflating class jp.wasabeef.richeditor.RichEditor
04-21 18:08:13.871: E/AndroidRuntime(15324): 	at android.view.LayoutInflater.createViewFromTag(Layo

```

**Comment by abfist** [comment]
turned out it was a problem with my layout and package names
