### ISSUE TITLE
In Editor, double tap and selecting the text getting crash in Samsung XCover 3

### ISSUE THREAD

**Issue by sackurise** [wasabeef/richeditor-android#199]
In the Editor, While typing the text it is formatted correctly.   When i try to select the text by double tapping the text, suddenly the app gets crash in Samsung XCover 3 devices.

Fatal Exception: android.content.res.Resources$NotFoundException: Resource ID #0x20b001a
       at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
       at android.content.res.Resources.getInteger(Resources.java:1097)
       at org.chromium.ui.base.DeviceFormFactor.a(SourceFile:8)
       at org.chromium.content.browser.selection.SelectionPopupControllerImpl.a(SourceFile:212)
       at awf.onCreateActionMode(SourceFile:15)
       at cdf.onCreateActionMode(SourceFile:6)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:3040)
       at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1160)
       at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:1116)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
       at android.view.View.startActionMode(View.java:7101)
       at can.a(SourceFile:1)
       at org.chromium.content.browser.selection.SelectionPopupControllerImpl.h(SourceFile:128)
       at ceg.a(SourceFile:31)
       at cdC.a(SourceFile:14)
       at aCs.run(Unknown Source:7)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by hardslk** [comment]
same issue.

**Comment by imidhuntv** [comment]
I'm also getting this error. Any help?

**Comment by Iamroushankumar** [comment]
I am facing the same problem

**Comment by hardslk** [comment]
I think you should use context of Application Context instead of activity or fragment context then May be It solve.
